config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: { omniauth_callbacks: 'omniauth'}
  root 'appointments#index'
  resources :appointments do
    collection do
      get :google_calendar
    end
  end

  get 'google_calendar/redirect', to: 'google_calendar#redirect', as: 'google_calendar_redirect'
  get 'google_calendar/callback', to: 'google_calendar#callback', as: 'google_calendar_callback'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  validates :appointment_id, presence: true, uniqueness: true
end

app/models/user.rb
require 'google/api_client/client_secrets'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers:[:google_oauth2]

  has_many :appointments

  def get_google_calendar_client
    client = Google::Apis::CalendarV3::CalendarService.new
    return unless (self.present? && self.google_calendar_access_token.present? && self.google_calendar_refresh_token.present?)
    secrets = Google::APIClient::ClientSecrets.new({
                                                     "web" => {
                                                       "access_token" => self.google_calendar_access_token,
                                                       "refresh_token" => self.google_calendar_refresh_token,
                                                       "client_id" => Rails.application.secrets.google_client_id,
                                                       "client_secret" => Rails.application.secrets.google_client_secret
                                                     }
                                                   })
    client.authorization = secrets.to_authorization
    client.authorization.grant_type = "refresh_token"

    client.authorization.refresh!
    self.update_columns(
      google_calendar_access_token: client.authorization.access_token,
      google_calendar_refresh_token: client.authorization.refresh_token,
      google_calendar_access_token_expires_in: client.authorization.expires_at.to_i
    )

    response = client.list_events("primary")

  end

  def self.create_from_provider_data(provider_data)
    email = provider_data.info.email
    first_name = provider_data.info.name.split(' ')[0]
    last_name = provider_data.info.name.split(' ')[1]
    password = Devise.friendly_token[0, 20]
    self.create(email: email, password: password,first_name: first_name,last_name: last_name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @appointments = current_user.appointments
  end

  def google_calendar
    @events = current_user.get_google_calendar_client
    if @events.present?
      @events.items.each do |event|
        appointment = current_user.appointments.find_by(appointment_id: event.id)
        if appointment.present?
          appointment.update(summary: event.summary,
                              start_date: event.start.date_time,
                              end_date: event.end.date_time,
                              status: event.status,
                              updated: event.updated)
        else
          current_user.appointments.create(summary: event.summary,
                                          start_date: event.start.date_time,
                                          end_date: event.end.date_time,
                                          appointment_id: event.id,
                                          status: event.status,
                                          html_link: event.html_link,
                                          created: event.created,
                                          updated: event.updated)
        end
      end
      redirect_to appointments_path, notice: "You are synced with Google calendar now."
    else
      redirect_to google_calendar_redirect_path
    end
  end
end

app/controllers/google_calendar_controller.rb
class GoogleCalendarController < ApplicationController
  before_action :authenticate_user!

  def redirect
    client = Signet::OAuth2::Client.new(client_options)
    redirect_to client.authorization_uri.to_s
  end

  def callback
    client = Signet::OAuth2::Client.new(client_options)
    client.code = params[:code]
    response = client.fetch_access_token!
    client.update!(response)

    current_user.update_columns(
      google_calendar_access_token: response["access_token"],
      google_calendar_access_token_expires_in: response["expires_in"],
      google_calendar_refresh_token: client.refresh_token.present? ? client.refresh_token : current_user.google_calendar_refresh_token,
    )

    response = current_user.get_google_calendar_client
    redirect_to root_path, notice: "You are synced with Google calendar now."
  end

  def client_options(options={})
    {
      client_id: Rails.application.secrets.google_client_id,
      client_secret: Rails.application.secrets.google_client_secret,
      authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
      token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
      scope: "#{Google::Apis::CalendarV3::AUTH_CALENDAR_READONLY}",
      redirect_uri: options[:redirect_uri] || google_calendar_callback_url
    }
  end

end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController

  def google_oauth2
    if registered_user.present?
      sign_in_and_redirect registered_user
    else
      failure
    end
  end

  def failure
    redirect_to new_user_registration_url, error: 'There is a problem signing you in'
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

  def registered_user
    email = auth_hash.info.email
    available_user = User.find_by(email: email)
    user = available_user.present? ? available_user : User.create_from_provider_data(auth_hash)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_index.html.erb
<td><%= @serial %></td>
<td><%= appointment.summary %></td>
<td><%= appointment.start_date.strftime("%d %B, %Y, %A") %></td>
<td><%= appointment.end_date.strftime("%d %B, %Y, %A") %></td>
<td><%= appointment.status %></td>
<td><%= appointment.created.strftime("%d %B, %Y, %A") %></td>
<td><%= appointment.updated.strftime("%d %B, %Y, %A") %></td>
<td><%= link_to 'Go to calendar', appointment.html_link %></td>

app/views/appointments/index.html.erb
<div>
  <h1 class="sync_button"><%= link_to "Sync Google Calendar", google_calendar_appointments_path %></h1>
  <h2 class="log_out_button"><%= link_to "Log Out", destroy_user_session_path %></h2>
</div>
<% if @appointments.empty? %>
  <h2>You have no appointments in Google Calendar.</h2>
<% else %>
  <h2>My Google Calendar Appointments</h2>
  <table>
    <tr>
      <th> #</th>
      <th> Summary</th>
      <th> Start Date</th>
      <th> End Date</th>
      <th> Status</th>
      <th> Created at</th>
      <th> Updated at</th>
      <th> Action</th>
    </tr>
    <% if @appointments.present? %>
      <% @serial = 1 %>
      <% @appointments.each do |appointment| %>
        <tr> <%= render partial: 'index', locals: {appointment: appointment} %> </tr>
        <% @serial += 1 %>
      <% end %>
    <% end %>
  </table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoogleCalendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>